version: "3"
#uses on github action
services:
  mongo:
    container_name: descriptors-wallet_mongo
    image: mongo
    ports:
      - 27018:27017 # for access
    networks:
      - back
    restart: always
    tty: true
    # bitcoind:
    #   container_name: descriptors-wallet_bitcoind
    #   image: kylemanna/bitcoind
    #   user: "1001:121"
    #   command: bitcoind -conf=/bitcoin/.bitcoin/bitcoin.regtest.conf
    #   volumes:
    #- ./config/bitcoin:/bitcoin/.bitcoin
    #     - $HOME/.bitcoin:/bitcoin/.bitcoin
    #   networks:
    #     - back
    #   restart: always
    #   tty: true

  api:
    container_name: descriptors-wallet_api
    build: ./
    ports:
      - 3000:3000
    depends_on:
      - "mongo"
    networks:
      - back
    restart: always
    tty: true

volumes:
  db_data:


networks:
  back:
    external: true
  front:
    external: true
