version: "3"

services:
  mongo:
    image: mongo
    ports:
      - 27018:27017 # for access
    networks:
      - back
    restart: always
    tty: true
    container_name: lb4-base_mongo_1

  api:
    build:
      context: ../../../
      dockerfile: ./config/docker/dev/start.Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - "mongo"
    networks:
      - back
    restart: always
    tty: true
    container_name: lb4-base_api_1

volumes:
  db_data:

networks:
  back:
    external: true
  front:
    external: true
