name: Run tests on development

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Download code
        run: git clone --branch development https://github.com/aitorjs/lb4-base/

      - name: Create env file
        run: |
          cd lb4-base/
          touch .env
          echo "ADMIN_EMAIL='root@email.com'" >> .env
          echo "ADMIN_PASS='passpass1'" >> .env
          echo "JWT_ACCESS_SECRET='myjwts3cr3t'" >> .env

      - name: Up test envirotment
        run: |
          cd lb4-base/
          docker network create back
          docker-compose up -d

      - name: Testing
        run: |
          cd lb4-base/
          docker exec lb4-base_api_1 npm run test
