name: Run tests on main

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-20.04

    steps:
      - name: Git checkout
        uses: actions/checkout@v2

      - name: Download code
        run: git clone https://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@github.com/biteskola/btc-explorer.git

      - name: Create env file
        run: |
          cd btc-explorer/
          touch .env
          echo "ADMIN_EMAIL='root@email.com'" >> .env
          echo "ADMIN_PASS='passpass1'" >> .env
          echo "JWT_ACCESS_SECRET='myjwts3cr3t'" >> .env

      - name: Up test envirotment
        run: |
          cd btc-explorer/
          docker network create back
          docker-compose up -d

      - name: Testing
        run: |
          cd btc-explorer/
          docker exec btc-explorer_api_1 npm run test
